<h1>Python: without numpy or sklearn </h1>

In [15]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [16]:
A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]

B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

# mtx_a_dim: Contains Matrix A shape
mtx_a_dim = dict({
    'rows': len(A),
    'columns': len(A[0])
})

# mtx_b_dim: Contains Matrix B shape
mtx_b_dim = dict(
    {
    'rows': len(B),
    'columns': len(B[0])
    }
)


def can_matrices_multiplied(mtx_i, mtx_ii):
    """Validate matrices dimension before matrix multiplication
    
    Parameters
    ----------
    mtx_i: 2-D Array
        Elemets in matrix `mtx_i`
        
    mtx_ii: 2-D Array
        Elemets in matrix `mtx_ii`
        
    Return
    ------
    is_valid: Boolean
        Wheather matrix multiplication is possible OR not
        True: Possible
        False: Not Possible
    """
    
    is_valid = False
    
    if mtx_a_dim.get('columns') == mtx_b_dim.get('rows'):
        is_valid = True
        
    return is_valid
    

def matrix_mul(A, B):
    """Matrix multiplication operation
    
    Parameters
    ----------
    A: 2-D Matrix
        Elements in matrix A

    B: 2-D Matrix
        Elements in matrix B

    Return
    ------
    res_mtx: Resultant matrix of matrix multiplication operation
    """

    res_mtx = []
    for row in range(mtx_a_dim.get('rows')):

        res_mtx.append([])
        for col in range(mtx_a_dim.get('columns')):
            
            element = 0
            for index in range(mtx_a_dim.get('rows')):

                element += A[row][index] * B[index][col]
            
            res_mtx[row].append(element)
            
        
    return(res_mtx)


"""
# do_multiplication: Flag to determine whether condition for matrix
    multiplication met or not
"""
do_multiplication = False
do_multiplication = can_matrices_multiplied(mtx_a_dim, mtx_b_dim)


if do_multiplication:
    print(matrix_mul(A, B))
else:
    print('Not possible')

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [4]:
import random

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

list_info = dict()
list_info = {
    'sum': sum(A),
    'length': len(A)
}

"""
list_i_prob: Contains probabilitites proportional to element magnitude in list `A`
"""
list_i_prob = [ item / list_info.get('sum') for item in A]

validation_obj = dict()
validation_obj = { item: 0 for item in A}


def pick_a_number_from_list(A, prob_list):
    """Randomly pick a number from a list with probability
    proportional to it's magnitude.

    Parameters
    ----------
    A: list

    Return
    ------
    res: list
        First element of list

    """
    res = random.choices(A, weights= prob_list, k=1)
    
    return res[0]


def sampling_based_on_magnitued(numbers, prob_list):
    """Perform n trials to randomly pick a number from a list

    Parameters
    ----------
    numbers: list
        
    prob_list: list
     Contains probablitites proportioanl to `prob_list` elements magnitude 

    Return
    ------
    validation_obj: dict
        Contains randomily pick number and their selecting frequency after 100 trials

    """    
    
    for i in range(1,100):
        
        number = pick_a_number_from_list(numbers, prob_list)
        
        update_item = validation_obj.get(number)
        validation_obj.update({number: int(update_item) + 1})
            
    return validation_obj
            

sampling_based_on_magnitued(A, list_i_prob)

{0: 0, 5: 0, 27: 6, 6: 1, 13: 3, 28: 10, 100: 34, 45: 13, 10: 2, 79: 30}

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [18]:
import re

String = '#2a$#b%c%561#'

def replace_digits(String):
    """Replace digits occurrance with symbol `#` and remove non digit
    characters with white space in given string

    Parameters
    ----------
    String: string


    Return
    ------
    res_string: string

    """

    res_string = ''
    
    matches = re.findall('[0-9]', String)
    matches_len = len(matches)
    
    if matches_len is not 0:
        res_string = '#'*matches_len
        
    return(res_string)
    

replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
s/pre>

In [9]:
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

max_marks = max(marks)

def check_data_sanity(list_i, list_ii):
    """Validate wether two list length are identical or not

    Parameters
    ----------
    list_i: list
    list_ii: list

    Return
    ------
        Boolean

    """
    
    return len(list_i) == len(list_ii)


def map_students_marks(students, marks):
    """Validate wether two list length are identical or not

    Parameters
    ----------
    students: list
        List of students
        
    marks: list
        Lsit of student's marks in `students` list

    Return
    ------
    mapped_entities: dict
        Individual student get mapped with obtained marks in exam

    """
    
    mapped_entities = dict(zip(students, marks))

    return mapped_entities


def display_dash_board(mapped_entities, max_marks, q1 = 0.25, q3 = 0.75):
    """Calculate
        1. Top 5 students
        2. Top bottom 5 students
        3. Students whose percentile between (0.25 to 0.75)

    Parameters
    ----------
    mapped_entities: dict
        Mapped students name with percentile

    max_marks: int
        Maximum marks obtained by individual student
        
    q1: float
        Interquartile A
        
    q3: flaot
        Interquartile B

    Return
    ------
        Top 5 students, Top bottom 5 students, Students whose percentile between (0.25 to 0.75)
    """
    
    sorted_res = sorted(mapped_entities, key = mapped_entities.get, reverse = True)
    
    # write code for computing top top 5 students
    top_5_students = sorted_res[:5]
    
    # write code for computing top least 5 students
    least_5_students = sorted_res[-1:-6:-1]
    
    # write code for computing top least 5 students
    students_within_25_and_75_dict = {
                                    key: mapped_entities[key]
                                    for key in mapped_entities
                                    if (mapped_entities[key] / max_marks > q1 and mapped_entities[key] / max_marks < q3)
                                }
    
    students_within_25_and_75 = sorted(students_within_25_and_75_dict, key = students_within_25_and_75_dict.get)


    return top_5_students, least_5_students, students_within_25_and_75


is_data_valid = False
is_data_valid = check_data_sanity(students, marks)

if is_data_valid:
    
    mapped_entities = map_students_marks(students, marks)

    top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(mapped_entities, max_marks)
    
    print(top_5_students)
    print(least_5_students)
    print(students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7']
['student3', 'student4', 'student9', 'student6', 'student1']
['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [13]:
import math

s = [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
p = (3,-4)

def compute_cosine_distance(s, p):
    """compute cosine distances between two points

    Parameters
    ----------
    s: list

    p: tuple
        point whose cosine distance needs to compute against points in `s`

    Return
    ------
    cosine_dist: list
        List contains cosine distance of `p` from multiple points in `s`
    """
    
    x, y = p
    
    dist_origin = math.sqrt(math.pow(x, 2) + math.pow(y, 2))
    
    cosine_dist = dict()
    for x1, y1 in s: 
        
        num = x * x1 + y * y1
        
        # Cosine distance formula
        den = math.sqrt(math.pow(x1, 2) + math.pow(y1, 2)) * dist_origin
        
        dist_cosine = math.degrees(math.acos(num / den))
        
        cosine_dist.update({(x1, y1): dist_cosine})
    
    return cosine_dist


def closest_points_to_p(dist_cosine, top_k):
    """Sort cosine distance list

    Parameters
    ----------
    dist_cosine: list
        
    top_k: int
        Top 5 distances
    :

    Return
    ------
    sorted_distance: list
        List contains top K cosine distance of point `p`
        from points in list `s`

    """    
    sorted_distance = sorted(dist_cosine, key = dist_cosine.get)
    
    return sorted_distance[:5]


dist_cosine = compute_cosine_distance(s, p)
points = closest_points_to_p(dist_cosine, 5)
points

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math
import re
import parser

red = [(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue = [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]

lines = ["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

def fit_line_eqn(coef_x, coef_y, interceptor, points):
    
    ref_list = list()
    for index, (coord_x, coord_y) in enumerate(points):

        code = compile('float(coef_x) * float(coord_x) +  float(coef_y) * float(coord_y) + float(interceptor)', 'file.py', 'eval')
        res = eval(code)

        is_pos = 1 if res > 0 else 0

        ref_list.append(is_pos)

    return ref_list

def are_list_items_different(list_items):
    
    return 1 if (len(list_items) == sum(list_items) or sum(list_items) == 0) else 0


def check_coord_on_line(red, blue, lines):
    
    final_res = []
    for line_eq in lines:

        coef_x, coef_y, interceptor = re.findall('[+-]?\d+.\d+|[+-]?\d+', line_eq)
    
        red_pts_res = fit_line_eqn(coef_x, coef_y, interceptor, red)
        red_pts_status = are_list_items_different(red_pts_res)
        
        blue_pts_res = fit_line_eqn(coef_x, coef_y, interceptor, blue)
        blue_pts_status = are_list_items_different(blue_pts_res)
        
        do_points_lie_on_either_side = 'Yes' if (red_pts_status and blue_pts_status) else 'No'

        final_res.append(do_points_lie_on_either_side)

    return final_res
        
        
res = check_coord_on_line(red, blue, lines)
res

['Yes', 'No', 'No', 'Yes']

<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [15]:
import re

s = "80,_,_,_,_"

def curve_smoothing(s):
    """Filling the missing values in the string with specified formate

    Parameters
    ----------
    s: string

    Return
    ------
    join_string: string    
        string with specified formate
    """

    
    list_items = s.split(',')

    is_first = True
    last_num = 0

    placeholder_count = 0

    updated_items = []
    for index, item in enumerate(list_items):

        if item == '_':
            placeholder_count += 1
        else:

            parsed_item = float(item)

            """
            To handle first iteration of below input string patterns
                s = "40,_,_,_,60"
                (OR)
                s = "80,_,_,_,_"
                (OR)
                s = "2_,_,30,_,_,_,50,_,_"
            """
            if is_first and last_num == 0 and index == 0:
                placeholder_count += 1
                is_first, last_num = False, parsed_item


            elif is_first and last_num == 0:
                """
                To handle first iteration of below input string patterns
                    s = "_,_,_,60"
                    (OR)
                    s = "_,_,30,_,_,_,50,_,_"
                """                

                placeholder_count += 1

                val = parsed_item / placeholder_count
                updated_items.extend( [val] * placeholder_count )

                placeholder_count = 1
                is_first = False
                last_num = val


            else:
                """
                To handle after first iteration of below input string patterns
                    s = "_,_,_,60"
                    (OR)
                    s = "_,_,30,_,_,_,50,_,_"
                    (OR)
                    s = "80,_,_,_,_"
                    (OR)
                    s = "2_,_,30,_,_,_,50,_,_"
                """


                placeholder_count += 1

                val = (last_num + parsed_item) / placeholder_count

                if len(updated_items) > 0:
                    updated_items.pop()

                updated_items.extend( [val] * placeholder_count )

                placeholder_count, last_num = 1, val
    """
    To handle last operation of below input string patterns
        s = "_,_,30,_,_,_,50,_,_"
        (OR)
        s = "80,_,_,_,_"
    """
    if placeholder_count > 0:

        val = last_num / placeholder_count

        if len(updated_items) > 0:
            updated_items.pop()

        updated_items.extend( [val] * placeholder_count )
    
    """
    Join list items with comma separated
    """
    join_string = ','.join([str(item) for item in updated_items])
    
    return join_string
        
        
curve_smoothing(s)

'16.0,16.0,16.0,16.0,16.0'

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [7]:
from functools import reduce

events = [['F1','S1'], ['F2','S2'], ['F3','S3'], ['F1','S2'], ['F2','S3'], ['F3','S2'], ['F2','S1'], ['F4','S1'], ['F4','S3'], ['F5','S1']]

def compute_ev1_ev2_maapings(events):
    """Compute mapping
        1. Between two events based on their simulatneously occurrences
        2. Individual event with their occurring

    Parameters
    ----------
    events: list(list())
        Each sublist contains two events occuuring together

    Return
    ------
    ev1_intsec_ev2: dict
        Contains events mapping to compute wether two events occur simultaneously or not
    
    ev2_occurance: dict
        Contains events 2 mapping with their occurrences count

    """


    """
    ev2_occurance: dict
        Contains events 2 mapping with their occurrences count
    """
    ev2_occurance = dict()
    for ev1, ev2 in events:
        
        """
        Map second event (ev2) { In ['F1','S1'] it's 'S1'}
            with its occuurences
        """
        if ev2 in ev2_occurance:

            temp = ev2_occurance[ev2]
            ev2_occurance.update({ev2: temp + 1})
        else:

            ev2_occurance.update({ev2: 1})


        """
        ev1_intsec_ev2: dict
            Contains events mapping to compute wether two events occur simultaneously or not
        """
        ev1_intsec_ev2 = dict()

        """
        In below code block we'll compute mapping between eve1 and ev2, to determine
        that given two events occurr simultaneously or not
        Mspping structure
        {
            'F1':{
                'S1':{
                    'count':1
                },
                'S2':{
                    'count':1
                }                
            },
        }
        """            
        if ev1 in ev1_intsec_ev2:

            temp_dict = dict()
            temp_dict = ev1_intsec_ev2.get(ev1)

            if ev2 in temp_dict:

                last_count = temp_dict[ev2]['count']
                temp_dict[ev2].update({'count': last_count + 1})
            else:

                temp_dict.update({ev2: {'count': 1}})

            ev1_intsec_ev2[ev1].update(temp_dict)

        else:

            ev1_intsec_ev2[ev1] = dict({ ev2:{'count':1} })
            
    return ev1_intsec_ev2, ev2_occurance


def get_nested_key(union_dict, key):
    """Pass nested keys as list and get corresponding value

    Parameters
    ----------
    union_dict: dict
        Dictionary of events mapping to determine wether two events
        occurr simultaneously or not
    key: list
        Nested keys as list


    Return
    ------
        Value of object at nested keys

    """

    return union_dict.get(key, 0)


def compute_cond_probabilities(events, ev1_intsec_ev2, ev2_occurance):
    """Compute conditional probabilities

    Parameters
    ----------
    events: list
    
    ev1_intsec_ev2: dict
    
    ev2_occurance: dict

    Return
    ------
    prob: list(tuple())
        Compute conditional probabilities against input list

    """

    prob = list()
    for ev1, ev2 in events:
        
        temp_keys = list([ev1, ev2, 'count'])
        conditional_prob = 0
        
        ev1_intsec_ev2_count = reduce(get_nested_key, temp_keys, ev1_intsec_ev2)
        
        ev2_count = ev2_occurance.get(ev2, 0)
        
        if ev2_count > 0:
            
            conditional_prob = ev1_intsec_ev2_count / ev2_count

        prob.append((ev1, ev2, conditional_prob))

    return prob


ev1_intsec_ev2, ev2_occurance = compute_ev1_ev2_maapings(events)

res = compute_cond_probabilities(events, ev1_intsec_ev2, ev2_occurance)

for record in res:
    ev1, ev2, res = record
    print("P(F={ev1}|S=={ev2})={res}".format(ev1 = ev1, ev2 = ev2, res = res))    

P(F=F1|S==S1)=0.25
P(F=F2|S==S2)=0.3333333333333333
P(F=F3|S==S3)=0.3333333333333333
P(F=F1|S==S2)=0.3333333333333333
P(F=F2|S==S3)=0.3333333333333333
P(F=F3|S==S2)=0.3333333333333333
P(F=F2|S==S1)=0.25
P(F=F4|S==S1)=0.25
P(F=F4|S==S3)=0.3333333333333333
P(F=F5|S==S1)=0.25


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [1]:
def intersection_operation(dict_i, dict_ii):
    
    return dict_i & dict_ii


def difference_operation(dict_i, dict_ii):
    
    return dict_i.difference(dict_ii)


def string_features(s1, s2):
    
    s1_dict = { word_i for word_i in s1.split() }
    s2_dict = { word_i for word_i in s2.split() }

    a = intersection_operation(s1_dict, s2_dict)
    
    b = difference_operation(s1_dict, s2_dict)
    
    c = difference_operation(s2_dict, s1_dict)
    
    
    return a, b, c



s1 = "the first column F will contain only 5 uniques values"
s2 = "the second column S will contain only 3 uniques values"

a, b, c = string_features(s1, s2)
print(a)
print(b)
print(c)

{'the', 'will', 'column', 'only', 'values', 'uniques', 'contain'}
{'first', 'F', '5'}
{'S', '3', 'second'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [4]:
import math

def compute_log_loss(a):
    
    loss = 0
    for y, y_score in a:
        
        loss += (y * math.log10(y_score) + (1 - y) * (math.log10(1 - y_score)))
    
    return -1 * loss/len(a)


a = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(a)
print(loss)

0.42430993457031635
