<h1>Python: without numpy or sklearn </h1>

In [15]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [16]:
A = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]

B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

mtx_a_dim = dict({
    'rows': len(A),
    'columns': len(A[0])
})

mtx_b_dim = dict(
    {
    'rows': len(B),
    'columns': len(B[0])
    }
)

def can_matrices_multiplied(mtx_i, mtx_ii):
    
    is_valid = False
    
    if mtx_a_dim.get('columns') == mtx_b_dim.get('rows'):
        is_valid = True
        
    return is_valid
    
    
# here A and B are list of lists
def matrix_mul(A, B):
    
    res_mtx = []
    for row in range(mtx_a_dim.get('rows')):

        res_mtx.append([])
        for col in range(mtx_a_dim.get('columns')):
            
            element = 0
            for index in range(mtx_a_dim.get('rows')):

                element += A[row][index] * B[index][col]
            
            res_mtx[row].append(element)
            
        
    return(res_mtx)


do_multiplication = False
do_multiplication = can_matrices_multiplied(mtx_a_dim, mtx_b_dim)


if do_multiplication:
    print(matrix_mul(A, B))
else:
    print('Not possible')

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [17]:
import random

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

list_info = dict()
list_info = {
    'sum': sum(A),
    'length': len(A)
}

list_i_prob = [ item / list_info.get('sum') for item in A]

validation_obj = dict()
validation_obj = { item: 0 for item in A}


def pick_a_number_from_list(A):
    
    res = random.choices(A, weights= list_i_prob, k=1)
    
    return res[0]


def sampling_based_on_magnitued(numbers):
    
    
    for i in range(1,100):
        
        number = pick_a_number_from_list(numbers)
        
        update_item = validation_obj.get(number)
        validation_obj.update({number: int(update_item) + 1})
            
    return validation_obj
            

sampling_based_on_magnitued(A)

{0: 0, 5: 1, 27: 10, 6: 5, 13: 6, 28: 8, 100: 26, 45: 12, 10: 4, 79: 27}

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [18]:
import re

String = '#2a$#b%c%561#'

def replace_digits(String):
    
    res_string = ''
    matches = re.findall('[0-9]', String)
    matches_len = len(matches)
    
    if matches_len is not 0:
        res_string = '#'*matches_len
        
    return(res_string)
    

replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
s/pre>

In [9]:
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

max_marks = max(marks)

def check_data_sanity(list_i, list_ii):
    
    return len(list_i) == len(list_ii)


def map_students_marks(students, marks):
    
    mapped_entities = dict(zip(students, marks))

    return mapped_entities


def display_dash_board(mapped_entities, max_marks, q1 = 0.25, q3 = 0.75):

    sorted_res = sorted(mapped_entities, key = mapped_entities.get, reverse = True)
    
    # write code for computing top top 5 students
    top_5_students = sorted_res[:5]
    
    # write code for computing top least 5 students
    least_5_students = sorted_res[-1:-6:-1]
    
    # write code for computing top least 5 students
    students_within_25_and_75_dict = {
                                    key: mapped_entities[key]
                                    for key in mapped_entities
                                    if (mapped_entities[key] / max_marks > q1 and mapped_entities[key] / max_marks < q3)
                                }
    
    students_within_25_and_75 = sorted(students_within_25_and_75_dict, key = students_within_25_and_75_dict.get)


    return top_5_students, least_5_students, students_within_25_and_75


is_data_valid = False
is_data_valid = check_data_sanity(students, marks)

if is_data_valid:
    
    mapped_entities = map_students_marks(students, marks)

    top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(mapped_entities, max_marks)
    
    print(top_5_students)
    print(least_5_students)
    print(students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7']
['student3', 'student4', 'student9', 'student6', 'student1']
['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [13]:
import math

s = [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
p = (3,-4)

def compute_cosine_distance(s, p):
    
    x, y = p
    dist_origin = math.sqrt(math.pow(x, 2) + math.pow(y, 2))
    
    cosine_dist = dict()
    for x1, y1 in s: 
        
        num = x * x1 + y * y1
        den = math.sqrt(math.pow(x1, 2) + math.pow(y1, 2)) * dist_origin
        
        dist_cosine = math.degrees(math.acos(num / den))
        
        cosine_dist.update({(x1, y1): dist_cosine})
    
    return cosine_dist


def closest_points_to_p(dist_cosine, top_k):
    
    sorted_distance = sorted(dist_cosine, key = dist_cosine.get)
    
    return sorted_distance[:5]


dist_cosine = compute_cosine_distance(s, p)
points = closest_points_to_p(dist_cosine, 5)
points #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math
import re
import parser

red = [(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue = [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]

lines = ["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

def fit_line_eqn(coef_x, coef_y, interceptor, points):
    
    ref_list = list()
    for index, (coord_x, coord_y) in enumerate(points):

        code = compile('float(coef_x) * float(coord_x) +  float(coef_y) * float(coord_y) + float(interceptor)', 'file.py', 'eval')
        res = eval(code)

        is_pos = 1 if res > 0 else 0

        ref_list.append(is_pos)

    return ref_list

def are_list_items_different(list_items):
    
    return 1 if (len(list_items) == sum(list_items) or sum(list_items) == 0) else 0


def check_coord_on_line(red, blue, lines):
    
    final_res = []
    for line_eq in lines:

        coef_x, coef_y, interceptor = re.findall('[+-]?\d+.\d+|[+-]?\d+', line_eq)
    
        red_pts_res = fit_line_eqn(coef_x, coef_y, interceptor, red)
        red_pts_status = are_list_items_different(red_pts_res)
        
        blue_pts_res = fit_line_eqn(coef_x, coef_y, interceptor, blue)
        blue_pts_status = are_list_items_different(blue_pts_res)
        
        do_points_lie_on_either_side = 'Yes' if (red_pts_status and blue_pts_status) else 'No'

        final_res.append(do_points_lie_on_either_side)

    return final_res
        
        
res = check_coord_on_line(red, blue, lines)
res

['Yes', 'No', 'No', 'Yes']

<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [14]:
count = 0
count += 1
print(count)

1


In [15]:
count = []
count.extend([3]*3)
count

[3, 3, 3]

In [25]:
import re
# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

#s = "_,_,30,_,_,_,50,_,_"
#s = "40,_,_,_,60"
s = "80,_,_,_,_"

#placeholder_grp_list = re.findall('[_,]+', s)
#placeholder_sub = [len(re.findall('[_]+', placeholder)) for placeholder in placeholder_grp_list]

#print(placeholder_sub)
#nums = re.findall('\d+', s)
#nums = [int(num) for num in nums]

list_items = s.split(',')

is_first = True
last_num = 0

placeholder_count = 0

updated_items = []
for index, item in enumerate(list_items):
    
    if item == '_':
        placeholder_count += 1
    else:
        
        parsed_item = float(item)
        
        if is_first and last_num == 0 and index == 0:
            placeholder_count += 1
            is_first, last_num = False, parsed_item
            
        elif is_first and last_num == 0:
            
            placeholder_count += 1
            
            val = parsed_item / placeholder_count
            updated_items.extend( [val] * placeholder_count )
            
            placeholder_count = 1
            is_first = False
            last_num = val
            
        else:
            
            placeholder_count += 1
            
            val = (last_num + parsed_item) / placeholder_count
            
            if len(updated_items) > 0:
                updated_items.pop()

            updated_items.extend( [val] * placeholder_count )
            
            placeholder_count, last_num = 1, val

if placeholder_count > 0:
    
    val = last_num / placeholder_count
    
    if len(updated_items) > 0:
        updated_items.pop()

    updated_items.extend( [val] * placeholder_count )
        
print(updated_items)

[16.0, 16.0, 16.0, 16.0, 16.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [1]:
def intersection_operation(dict_i, dict_ii):
    
    return dict_i & dict_ii


def difference_operation(dict_i, dict_ii):
    
    return dict_i.difference(dict_ii)


def string_features(s1, s2):
    
    s1_dict = { word_i for word_i in s1.split() }
    s2_dict = { word_i for word_i in s2.split() }

    a = intersection_operation(s1_dict, s2_dict)
    
    b = difference_operation(s1_dict, s2_dict)
    
    c = difference_operation(s2_dict, s1_dict)
    
    
    return a, b, c



s1 = "the first column F will contain only 5 uniques values"
s2 = "the second column S will contain only 3 uniques values"

a, b, c = string_features(s1, s2)
print(a)
print(b)
print(c)

{'the', 'will', 'column', 'only', 'values', 'uniques', 'contain'}
{'first', 'F', '5'}
{'S', '3', 'second'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [4]:
import math

def compute_log_loss(a):
    
    loss = 0
    for y, y_score in a:
        
        loss += (y * math.log10(y_score) + (1 - y) * (math.log10(1 - y_score)))
    
    return -1 * loss/len(a)


a = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(a)
print(loss)

0.42430993457031635
